# Generated by Django 5.2.7 on 2025-11-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='comprador_nome',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='qr_code',
            field=models.CharField(default='sem_qrcode', max_length=200),
            preserve_default=False,
        ),
    ]
